"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const appointment_controller_1 = require("../controllers/appointment.controller");
const router = (0, express_1.Router)();
router.get('/', appointment_controller_1.appointmentController.getAll);
router.get('/:id', appointment_controller_1.appointmentController.getById);
router.post('/', appointment_controller_1.appointmentController.create);
router.put('/:id', appointment_controller_1.appointmentController.update);
router.delete('/:id', appointment_controller_1.appointmentController.remove);
exports.default = router;
