"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const asset_controller_1 = require("../controllers/asset.controller");
const router = (0, express_1.Router)();
router.get('/', asset_controller_1.getAll);
router.get('/:id', asset_controller_1.getById);
router.post('/', asset_controller_1.create);
router.put('/:id', asset_controller_1.update);
router.delete('/:id', asset_controller_1.remove);
exports.default = router;
