"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const router = (0, express_1.Router)();
router.post('/register', auth_controller_1.authController.register);
router.post('/login', auth_controller_1.authController.login);
router.post('/reset-password', auth_controller_1.authController.resetPassword);
router.post('/verify_token', auth_controller_1.authController.verifyToken);
exports.default = router;
