"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const cvdata_controller_1 = require("../controllers/cvdata.controller");
const router = (0, express_1.Router)();
router.get('/', cvdata_controller_1.cvDataController.getAll);
router.get('/:id', cvdata_controller_1.cvDataController.getById);
router.post('/', cvdata_controller_1.cvDataController.create);
router.put('/:id', cvdata_controller_1.cvDataController.update);
router.delete('/:id', cvdata_controller_1.cvDataController.remove);
exports.default = router;
