"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const project_controller_1 = require("../controllers/project.controller");
const router = (0, express_1.Router)();
router.get('/', project_controller_1.projectController.getAll);
router.get('/:id', project_controller_1.projectController.getById);
router.post('/', project_controller_1.projectController.create);
router.put('/:id', project_controller_1.projectController.update);
router.delete('/:id', project_controller_1.projectController.remove);
router.post('/skill-requirements', project_controller_1.projectController.createSkillRequirement);
router.put('/skill-requirements/:id', project_controller_1.projectController.updateSkillRequirement);
router.delete('/skill-requirements/:id', project_controller_1.projectController.deleteSkillRequirement);
exports.default = router;
